### ISSUE TITLE
Ship editor X-positioning bug?

### ISSUE THREAD

**Issue by ZombieEnderman5** [pmgl/starblast-modding#11]
I can't understand what exactly is the cause of this... I've made the angle as straight as my browser will allow.
![image](https://user-images.githubusercontent.com/37218872/42709676-3e701526-86af-11e8-8815-6bfb24ef7e6b.png)
If you look at the image, the `main` body of this ship is positioned towards the right X-positioned `curved_ deco` body. `main` is at `0, 0, 0` (X, Y, Z) offset, while the offsetted `curved_deco` bodies are at `95, -40, -5` offset.

**Comment by GatoCreador887** [comment]
No, it isn't curved

**Comment by ZombieEnderman5** [comment]
I say "curved" because the actual body is named that. Oh, and they have an angle of `-45` degrees... I wonder if that's my problem :thinking:

**Comment by GatoCreador887** [comment]
The main body is not curved. It may look like that though due to the way we humans see, due to the horizontal layout of our eyes maybe. But it is not curved.

**Comment by GatoCreador887** [comment]
So can someone close this issue?

**Comment by ZombieEnderman5** [comment]
Ah... That's why you deleted your previous comment.

**Comment by ZombieEnderman5** [comment]
I'll close it.
