### ISSUE TITLE
Dueling Mode - REMOVE the A-Speeder!

### ISSUE THREAD

**Issue by danallen82** [pmgl/starblast-modding#25]
Dueling mode is my favorite mod, but the A-Speeder ruins the variety of ship gameplay. There is no other baseline ship, so why should the A be in there? Add in the Advanced Fighter and O-defender if you keep the A-speeder. It isn't fun when people only use A-speeders which are imbalanced in dueling.

Also you need to make more commands that help with invitations. Remove loser, winner. Instead add "Invite" and "Join" because random selection isn't balanced.

**Comment by Bhpsngum** [comment]
This is only the repository of the general Starblast Modding itself, if you want to ask any questions about a specific mod, please head to the Discord server of that mod. We are not going to answers relating to them here.
